//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Php.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Php.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _in {
            get {
                object obj = ResourceManager.GetObject("_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _out {
            get {
                object obj = ResourceManager.GetObject("_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap phpabout {
            get {
                object obj = ResourceManager.GetObject("phpabout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;title&gt;网站扫描报告&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gb2312&quot;&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///&lt;!-- 
        ///table{
        ///font-size:76%
        ///}
        ///.STYLE2 {
        ///	color: #FF0000;
        ///	font-weight: bold;
        ///}
        ///.STYLE3 {
        ///	color: #009933;
        ///	font-weight: bold;
        ///}
        ///.STYLE5 {color: #999999; font-weight: bold; }
        ///.STYLE7 {color: #FF9900; font-weight: bold; }
        ///.STYLE9 {color: #FF6600; font-weight: bold; }
        ///--&gt;
        ///&lt;/style&gt;
        ///&lt;body&gt;
        ///&lt;h2 align=&quot;center&quot;&gt;网站扫描报告&lt;/h2&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tmpl {
            get {
                return ResourceManager.GetString("tmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;gb2312&quot;?&gt;
        ///&lt;AutoUpdater&gt;
        ///  &lt;description&gt;Application autoUpdate&lt;/description&gt;
        ///  &lt;Updater&gt;
        ///    &lt;Url&gt;http://down.zy13.net/php/&lt;/Url&gt;
        ///	&lt;LastUpdateTime&gt;2020-05-20&lt;/LastUpdateTime&gt;
        ///  &lt;/Updater&gt;
        ///  &lt;Application&gt;
        ///     &lt;EntryPoint&gt;PHP漏洞扫描.exe&lt;/EntryPoint&gt;
        ///	 &lt;Location&gt;.&lt;/Location&gt;
        ///     &lt;Version&gt;1.0.0&lt;/Version&gt;
        ///  &lt;/Application&gt;
        ///  &lt;Files&gt;
        ///	   &lt;File Ver=&quot;1.0.0&quot; Name=&quot;PHP漏洞扫描.exe&quot; /&gt;
        ///  &lt;/Files&gt;
        ///&lt;/AutoUpdater&gt; 的本地化字符串。
        /// </summary>
        internal static string UpdateList {
            get {
                return ResourceManager.GetString("UpdateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 在线更新 {
            get {
                object obj = ResourceManager.GetObject("在线更新", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
